function tableout = importfile5(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE5 Import data from a spreadsheet
%   DATA = IMPORTFILE5(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   table.
%
%   DATA = IMPORTFILE5(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE5(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   pilotdata = importfile5('pilot_data.xlsx','maelle',2,746);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2021/12/20 07:22:50

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 746;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:AT%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:AT%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,4,6,7,10,11,12,13,14,15,16,17,18,19,20]);
raw = raw(:,[2,3,5,8,9,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Create table
tableout = table;

%% Allocate imported array to column variable names
tableout.trial_type = cellVectors(:,1);
tableout.trial_index = data(:,1);
tableout.time_elapsed = data(:,2);
tableout.internal_node_id = cellVectors(:,2);
tableout.rt = data(:,3);
tableout.stimulus = cellVectors(:,3);
tableout.response = cellVectors(:,4);
tableout.success = data(:,4);
tableout.timeout = data(:,5);
tableout.failed_images = cellVectors(:,5);
tableout.failed_audio = cellVectors(:,6);
tableout.failed_video = cellVectors(:,7);
tableout.view_history = cellVectors(:,8);
tableout.letters = cellVectors(:,9);
tableout.cued_row = cellVectors(:,10);
tableout.cued_let = cellVectors(:,11);
tableout.block_no = cellVectors(:,12);
tableout.grid = cellVectors(:,13);
tableout.inverted_trial = cellVectors(:,14);
tableout.spec_let_pos = cellVectors(:,15);
tableout.spec_let_id = data(:,6);
tableout.cued_letters = data(:,7);
tableout.grid_lower = data(:,8);
tableout.cued_letters_lower = data(:,9);
tableout.correct_loc = data(:,10);
tableout.correct_row = data(:,11);
tableout.in_grid = data(:,12);
tableout.not_in_grid = data(:,13);
tableout.guess = data(:,14);
tableout.subj_entries = data(:,15);
tableout.alternatives = data(:,16);
tableout.order = data(:,17);
tableout.correct = data(:,18);
tableout.sel_option = data(:,19);
tableout.upr_selupr = data(:,20);
tableout.upr_selinv = data(:,21);
tableout.inv_selinv = data(:,22);
tableout.inv_selupr = data(:,23);
tableout.nshown_upr = data(:,24);
tableout.nshown_inv = data(:,25);
tableout.block_number = data(:,26);
tableout.recall = data(:,27);
tableout.recog = data(:,28);
tableout.recall_perc = data(:,29);
tableout.recog_perc = data(:,30);
tableout.question_order = data(:,31);

